### ISSUE TITLE
BCA Operation failed 12.1.0.2

### ISSUE THREAD

**Issue by dionisioC** [biemond/biemond-em-12c#1]
Using Vagrant 1.8.4 and Virtualbox 5.0.24 (I updated just in case)

I have downloaded this repository, and just updated the software path and added the files

It ends with the following error

==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/File[/var/tmp/install/database_oraDb.rsp]/ensure: created
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: Copying database files
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 1% complete
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 2% complete
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 4% complete
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: DBCA Operation failed.
==> emdb: Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: Look at the log file "/oracle/cfgtoollogs/dbca/emrepos/emrepos.log" for further details.
==> emdb: Error: /oracle/product/12.1/db/bin/dbca -silent -responseFile /var/tmp/install/database_oraDb.rsp returned 1 instead of one of [0]
==> emdb: Error: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: change from notrun to 0 failed: /oracle/product/12.1/db/bin/dbca -silent -responseFile /var/tmp/install/database_oraDb.rsp returned 1 instead of one of [0]

The file /oracle/cfgtoollogs/dbca/emrepos/emrepos.log contains

Database Configuration Assistant failed to detect options for this Oracle Installation.
ORA-12547: TNS:lost contact

Due to this failure some Database Configuration Assistant features will not be available. Do you want to continue?

Unique database identifier check passed.

/ has enough space. Required space is 6140 MB , available space is 58817 MB.
File Validations Successful.
Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 2%
ORA-12547: TNS:lost contact

DBCA_PROGRESS : 4%
Error while cataloging RMAN Backups
DBCA_PROGRESS : DBCA Operation failed.

Any help is appreciated

**Comment by biemond** [comment]
Hi,

I think it is a common problem with creating a Oracle database and virtualization, somehow it loses the connection to the DB. I saw it on docker and in virtualbox.

I am using vmware but it can be some hostname, network or strange vbox routing problem (nat, bridge etc).

Hope this helps.

thanks Edwin

**Comment by dionisioC** [comment]
Thanks for your answer, I will keep trying, and If I find a solution I will update this

**Comment by dionisioC** [comment]
There is an issue related with this

https://forums.virtualbox.org/viewtopic.php?f=8&t=76375

The workaround seems to be here

https://www.virtualbox.org/ticket/14427

But for the purposes of doing an automatic installation is not a good workaround, so I would suggest is someone faces the same problem just downgrade to virtualbox 4 the last release until that ticket is closed, I did it and it worked.

Thanks for the answer
